### ISSUE TITLE
Search doesn't return expected results with some characters

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#180]
**Describe the issue**
On the Chinese news item listing, the search form doesn't return the right results. Some of the news contain the following characters '工作组备忘' in their titles. However, searching for that string returns 0 results.
Note that the first 3 characters do return some results so it seems to be a problem with some characters only.

**URL**
https://www-staging.w3.org/zh-hans/news/
https://www-staging.w3.org/zh-hans/news/?search=%E5%B7%A5%E4%BD%9C%E7%BB%84%E5%A4%87%E5%BF%98

/cc @xueyuanjia

**Comment by xueyuanjia** [comment]
hi @jean-gui I gave it a try a few minutes ago. When I search for "工作组备忘" on current [chinaw3c.org](https://www.chinaw3c.org), I see [plenty results](https://www.chinaw3c.org/search/工作组备忘/). However, searching with the same characters, the [new site](https://www-staging.w3.org/zh-hans/news/) only return [one result](https://www-staging.w3.org/zh-hans/news/?search=工作组备忘). The issue seems still exist...

**Comment by jean-gui** [comment]
Hmm, rebuilding the search index is actually more involved than I thought, and pretty slow. The process is running, I'll let you know when it finished.

**Comment by jean-gui** [comment]
@deniak @xueyuanjia The issue should now be fixed, see https://www.w3.org/zh-hans/news/?search=%E5%B7%A5%E4%BD%9C%E7%BB%84%E5%A4%87%E5%BF%98

Fixed by https://github.com/w3c/w3c-website-frontend/commit/3c293ad0417e439422ce322a96c97b9cca02bc37
