### ISSUE TITLE
/TR information density too low

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#207]
**Describe the issue**
The list of standards on https://beta.w3.org/TR/ is formatted in a way that is very low density and this makes it difficult to scan the list. It's very possible to end up with a very long list of standards when browsing or when searching for e.g. CSS.

**To reproduce**
See https://beta.w3.org/TR/

**Expected behavior**
A compact list of specs that is easily scannable.

**Screenshots**

**Additional context**
Pretty sure this issue was raised earlier in the design cycle, but I can't find it.

**Comment by NicolaSaunders** [comment]
I have been discussing this with one of our designers. Here's a summary of their thoughts and suggestions:

***

This page does have generous linespacing and contain a lot of information but whether it is 'low density' or difficult to scan is subjective.

It would be hard to reduce the line-height without negatively affecting the hit area and affordance of the smaller hyperlinks.

The page will always be long due to the number of results, it feels appropriate for the results to spread over several screens. Using advanced filter options enables the user to focus the results, but this might not be obvious.

Some changes we could make:

- Better promote the 'Advanced filter options' with some lead text like, 'Our filter options can really help you find the reports you need.'
- Simplify the title 'Advanced filter options' to, 'Filter options'.
- Reduce vertical spacing by-
  - Reduce padding within `div.tr-list` to `padding-bottom: 0.5rem` and `padding-top: 1.25rem`
  - Remove bottom padding from `.technical-reports .hero`
  - Reduce top padding for `div.family-grouping` to `padding-top: 1.75rem`
- Add a border-bottom to every `div.tr-list_item` to improve consistency for scanning across groups, including those with single results (remove the current top border)

As an aside, the size of the H2 and H3 may be reduced slightly, if heading sizes are generally reduced across the website. (This has been mentioned a few times and will be reviewed.)

***

Shall we go ahead and make these changes? I attach before and after comparative screengrabs - they are quite long, but I thought they might be helpful to include.

Before:
![Screenshot showing original spacing on TR screen](https://github.com/user-attachments/assets/37b01ef8-a91e-4813-a3dd-862a4d3c54ec)

After:
![Screenshot showing reduced vertical spacing on TR screen](https://github.com/user-attachments/assets/f65b6e33-1dd1-45dd-b607-27b3d015edd1)

**Comment by gosko** [comment]
These changes all look good to me, except I don't think it's necessary to add the text to promote the filter options.

An extra change that I think would help improve the ability to scan the page quickly would be to omit the redundant spec titles in the lists of translations. If I remember correctly these were included to improve accessibility for users of screenreaders, but if that's the only reason maybe the spec titles for translations could be wrapped in a `span class=visuallyhidden`?

![Screen shot with redundant spec titles omitted](https://github.com/user-attachments/assets/5d8d739d-1e54-45de-a891-64a7cef6eca9)

I would prefer if the leading text were simply 'Translations:' instead of '2 translations, '5 translations'; I wonder if it would make sense to wrap the number of translations in `span class=visuallyhidden` as well?

e.g. `<span class=visuallyhidden>5 </span>Translations<span class=visuallyhidden> for Namespaces in XML 1.1 (Second Edition)</span>: ...`

We might also consider moving the lists of translations next to the publication date and history in the interest of reclaiming that vertical space:

![Screen shot with translations next to history](https://github.com/user-attachments/assets/2d91f501-4222-42a0-bf7e-f0982ba1f024)

@fantasai, interested to hear your thoughts.

**Comment by vivienlacourba** [comment]
cc: @deniak

**Comment by vivienlacourba** [comment]
> These changes all look good to me, except I don't think it's necessary to add the text to promote the filter options.

I agree with those improvements even if the vertical gain is limited (With these suggested changes I'm now seeing 6 specs on a single screen instead of the 5 and a half specs I can see today, so roughly a 9% increase).
I also agree with @gosko that the additional text to promote the filter options does not seem necessary.

> An extra change that I think would help improve the ability to scan the page quickly would be to omit the redundant spec titles in the lists of translations. If I remember correctly these were included to improve accessibility for users of screenreaders, but if that's the only reason maybe the spec titles for translations could be wrapped in a `span class=visuallyhidden`?

+1

> I would prefer if the leading text were simply 'Translations:' instead of '2 translations, '5 translations'; I wonder if it would make sense to wrap the number of translations in `span class=visuallyhidden` as well?

+1

> We might also consider moving the lists of translations next to the publication date and history in the interest of reclaiming that vertical space:

One one side we'll indeed reclaim some vertical space but I fear this would be less usable (mixing data related to dates and translations on the same line).

**Comment by NicolaSaunders** [comment]
Proposed solution is at https://github.com/w3c/w3c-website-templates-bundle/pull/155

These changes improve the content density. We recommend leaving the tags as they are for now.

**Comment by vivienlacourba** [comment]
Closing as the related PR was merged. As mentioned by @NicolaSaunders the size of headings will be reviewed globally on the website.

> As an aside, the size of the H2 and H3 may be reduced slightly, if heading sizes are generally reduced across the website. (This has been mentioned a few times and will be reviewed.)
