### ISSUE TITLE
Get Involved > E-commerce is confusing

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#209]
**Describe the issue**
When I opened the Get Involved drop-down, I found it a bit confusing that it listed areas of work, it wasn't immediately obvious what the connection was, and the relationship of that list of topics to the "Find ways to get involved" page and the "W3C Membership"/"Donate"/"Sponsoring W3C" items on the list was a bit confusing.

**To reproduce**
Click Get Involved drop-down

**Expected behavior**
I'm really not sure. I'm not sure I understand the focus of this section.

**Possible ideas**
I wonder if it would make sense to rename the section to "Join W3C" and then move the "W3C Membership" topic to the top of the list so there's some better context for the rest of the items in the list?

**Comment by gosko** [comment]
I agree, the list of business ecosystems with no context is confusing. (extra confusing for those of us using Firefox because the css break-after that is intended to split the menu in a more logical place is [not supported in Firefox](https://caniuse.com/mdn-css_properties_break-after_multicol_context))

When the nav system was being designed I suggested adding some text above the lists to provide context, like 'Browse our work by industry' but this was deemed unsuitable since those headings were not needed in other menus, and we had run out of development time at that point.

![earlier mockup of my suggested change](https://user-images.githubusercontent.com/7144396/220763546-b2daf588-88b6-42e4-aeb0-1080a9b887f0.png)

In terms of how to improve the menu given the current code, maybe it would help to add an item in the menu above the list of ecosystems titled 'Browse our work by industry' linked to the [ecosystem landing page](https://beta.w3.org/ecosystems/)?

Also I continue to think the links on the right side of that menu would be better phrased as calls to action, like 'Become a member', 'Make a donation', 'Sponsor an event', 'Join a group'. Adding '(restricted)' next to Member Home would reduce the surprise of that page being access-controlled, and might add some FOMO to inspire memberships. @koalie WDYT?

<img width="1191" alt="mockup of simple changes to improve the menu" src="https://user-images.githubusercontent.com/7144396/220763306-9ae2054c-8e90-4b7b-a069-e9680b806784.png">

**Comment by koalie** [comment]
The section is still called "get involved" because it's broader than just "join W3C".
Using call to action verbs is perfect for this section. All done.

<img width="762" alt="Screenshot 2023-11-16 at 13 21 42 " src="https://github.com/w3c/w3c-website/assets/3716853/efab1ced-6ce3-46ab-8da8-aa5ee097f69a">
