### ISSUE TITLE
agendabot can't see calendar agenda

### ISSUE THREAD

**Issue by TallTed** [w3c/w3c-website#396]
agendabot can't see the agenda on https://www.w3.org/events/meetings/493561b0-3a22-467f-8531-3c93ee3512f5/20230627T100000/

**URL**
[The URL where this problem occurs.](https://www.w3.org/events/meetings/493561b0-3a22-467f-8531-3c93ee3512f5/20230627T100000/)

**Recommended solution**
I'm not sure... that's part of the problem. Fix (or instructions) must be propagated to all Team Reps, Chairs, and similar — anyone who has edit permissions on https://www.w3.org/events/meetings/

**Additional context**

**Comment by pchampin** [comment]
> agendabot can't see the agenda on https://www.w3.org/events/meetings/493561b0-3a22-467f-8531-3c93ee3512f5/20230627T100000/

to be fair, I hardly can read it myself... :-/

One solution I can see to this issue is: don't use H1s (nor their markdown equivalent) in the agenda!

Another solution (more demanding for systeam) would be to ensure that the heading levels generated from the markdown text starts at h3, to keep consistent with the structure of the page.

**Comment by koalie** [comment]
I think it might be an agendabot issue so I roped in @bert-github who developed it.

Also, I concur regarding not using h1s in the agenda (but I don't know how easy/difficult this is to control when feeding the agenda to the event.)

**Comment by bert-github** [comment]
AgendaBot now knows where to look for agendas in the new layout of the W3C group calendar (see [AgendaBot issue 2](https://github.com/w3c/AgendaBot/issues/2)).

However, in this particular event, the new calendar layout also turned the agenda from a list with ‘#‘ marks,

    # Scribe
    # All minutes
    # Round the room
    # Remaining steps

into a series of H1 headings (due to the calendar's use of MarkDown) and, as @pchampin said above, the result doesn't read very much like an agenda.

I'm reluctant to teach AgendaBot to treat an H1 as an agenda item, because it might then misinterpret H1 headings in other calendars. And because of how ‘#’ looks, I expect people won't use it often.

But if you have more examples of H1 headings used as agenda items, please tell me. (Best is probably to raise an issue on the [AgendaBot repo](https://github.com/w3c/AgendaBot), or send me email. Or, if you raise an issue elsewhere, mention me, @bert-github, explicitly.)
