### ISSUE TITLE
HTML errors generated by the component 'Video media'

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#397]
The HTML validator returns two errors for the pages containing a video, both related to the <iframe> element: 
- 'Duplicate attribute title.'
- 'The frameborder attribute on the iframe element is obsolete. Use CSS instead.'

**URL**
https://www.w3.org/mission/ (see results at [1])
https://www.w3.org/membership/ (see results at [2])

[1] https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2Fmission%2F
[2] https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2Fmembership%2F

**Comment by NicolaSaunders** [comment]
I have started a branch at [hotfix/#397-video-component](https://github.com/w3c/w3c-website-templates-bundle/tree/hotfix/%23397-video-component) to address this issue. It removes the `frameborder` attribute from the iframe markup used in the video component.

I am now stuck though, because I cannot see where the duplicated `title` attribute is coming from. I can see there is an if/else statement in the Twig file which either uses the markup from which I have removed `frameborder` or uses some other iframe markup, which I cannot track down.

@jean-gui do you have any ideas on this?

**Comment by jean-gui** [comment]
@NicolaSaunders I think the duplicate title comes from the files in https://github.com/w3c/w3c-website-frontend/tree/main/templates/partials, all on line 23:
```twig
{% set params = {'iframe': component.videoUrl.code|preg_replace('/^<iframe/', '<iframe title="' ~ component.videoTitle|e('html_attr') ~ '"')} %}
```
I think I did that because Youtube wasn't setting the iframe title in the past. That may have changed recently.

Unless we want to force the iframe title to the one set in the CMS (do we?), this line should probably just be :
```twig
{% set params = {'iframe': component.videoUrl.code} %}
```

**Comment by NicolaSaunders** [comment]
@jean-gui Thanks for that.

YouTube does now set an iframe `title` but its default content (YouTube video player) is not descriptive enough, especially if there is more than one video on a page.

I don't know how likely it is for a Vimeo video to be added, but their embed code does not include an iframe `title`.

My opinion is that we should force it to use the one set in the CMS, which should probably be a mandatory field.

**Comment by NicolaSaunders** [comment]
I am reassigning this task to @JamieC24 as this has moved from a front end issue to more of a CMS issue
