### ISSUE TITLE
Tables style should not rely on scope attribute

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#648]
**Describe the issue**
The [table component](https://design-system.w3.org/styles/tables.html) relies on the `scope` attribute to style the headers.
```
th[scope="col"] {
  background-color: #024488;
  color: #fff;
}
```

Removing/Forgetting that attribute will remove the blue background.

**Recommended solution**
Updating the selector to `thead > th` will make that attribute optional and ensure all the tables have the same style.

**Additional request**
We might also need the same changes for [tables footer `tfoot`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot).

**Comment by NicolaSaunders** [comment]
This rule was originally intended in the spirit of "defensive coding", where the lack of the desired visual appearance was aimed at reminding the author of the markup to add the missing `scope="col"` attribute.

However, I have learned that the `scope` attribute is not as crucial as I had previously thought for headers in simple tables:
- https://adrianroselli.com/2023/02/avoid-spanning-table-headers.html#Verdict
- https://www.tpgi.com/short-note-on-scoping-mechanisms/

Plus, it was too restrictive to tie the style just to a column scope, when more complex tables may benefit from having the same styles for header cells with row scope. So I am happy to remove the scope attribute entirely for the `th` selector.

Since heading cells can exist in either `thead` or `tfoot` I don't see a need to reference either of those in the `th` selector.

Proposed fix is at https://github.com/w3c/w3c-website-templates-bundle/pull/148
