### ISSUE TITLE
Upgrade to Deployer 7

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-website#673]
We cannot deploy the design system anymore because Deployer's configuration has not been updated to Deployer 7 yet.

I think the most problematic thing is the task `local:build` which is supposed to run locally, but it seems that it's not possible to run tasks locally anymore.

[The upgrade documentation](https://deployer.org/docs/7.x/UPGRADE) mentions that local() has to be replace by `once()` and `runLocally()`, but [it does not seem to work with a task, only with commands](https://deployer.org/docs/7.x/api#runlocally).

Can you look into this?

Thanks

**Comment by simonrjones** [comment]
@jean-gui  we made a load of updates to https://github.com/studio24/deployer-recipes a few months ago to support Deployer 7, which you may already be using. If you’re not, we’re happy to go through this or help update the `deploy.php` file as part of the retainer.

Our approach has been to use a starting deployer script (e.g. https://github.com/studio24/deployer-recipes/blob/main/recipe/symfony.php) and then add setup on top of that. 

My understanding of runLocally is it’s a function call to run a command. So that needs to be in your task where you build the files. 

Do you have a branch where you’ve been updating to Deployer 7 we can review?

**Comment by jean-gui** [comment]
I've just pushed what I've started to do at https://github.com/w3c/w3c-website-templates-bundle/pull/151.

The problematic function is at https://github.com/w3c/w3c-website-templates-bundle/pull/151/files#diff-2198d1e85a940e73e4ff9e445476a2dad5a26bb5f4e935d8bcbd73bb8bdf8af7L134, I don't know how to transform the call to `local()`.

**Comment by simonrjones** [comment]
Updated the `deploy.php` file, though I cannot fully test this due to access to the deployment server.

**Comment by simonrjones** [comment]
Fixed in PR https://github.com/w3c/w3c-website-templates-bundle/pull/151
