### ISSUE TITLE
Truncated "Related Pages" section in Invited Experts page

### ISSUE THREAD

**Issue by tidoust** [w3c/w3c-website#684]
**Describe the issue**
The Invited Experts page ends with a "Related pages" section. The section title appears truncated.

**URL**
https://www.w3.org/invited-experts/

**Recommended solution**
The section is empty in practice, so perhaps the fix is to simply drop it.

**Comment by vivienlacourba** [comment]
> **Describe the issue** The Invited Experts page ends with a "Related pages" section. The section title appears truncated.
> 
> **URL** https://www.w3.org/invited-experts/

Screenshot showing this issue:
![image](https://github.com/user-attachments/assets/a9f3060f-b004-4989-8142-e3f983d9aac5)

@NicolaSaunders can you look at this display issue?

> **Recommended solution** The section is empty in practice, so perhaps the fix is to simply drop it.

Indeed in the CMS there are no related pages defined, but the `"Display the "you may also like" listing?"` setting is set to "Yes".

@jean-gui this also produced some non-optimal markup as there is an empty `<p>`  section (because _"You May Also Like Section Introduction"_ is not set) and an empty `<ul>` list (because there are no `"You May Also Like Related Entries"`). Can you add the missing tests so that empty paragraph or lists are not added.

```html
<aside class="crosslinks">
    <div class="l-center">
        <div class="component component--columns component--columns--images">
            <div class="component--columns__intro">
                <h2>Related pages</h2>
                <p></p>
            </div>
            <ul class="clean-list" role="presentation">
            </ul>
        </div>
    </div>
</aside>
```

**Comment by NicolaSaunders** [comment]
@vivienlacourba The display issue is caused by the empty `<ul>` which is obscuring the `<h2>` so addressing the markup to avoid adding empty elements as you suggest will resolve that.

**Comment by jean-gui** [comment]
Fixed.
