### ISSUE TITLE
Warning stays displayed

### ISSUE THREAD

**Issue by MarioBatusic** [w3c/w3c-website#698]
**Describe the issue**
I have rejoined the re-charted ARIA Working Group for my organisation "Fabasoft", but the Warning stays displayed on the [Fabasoft page](https://www.w3.org/organizations/89490/users/#main).

**Comment by vivienlacourba** [comment]
@deniak I confirm seeing that message displayed right after @MarioBatusic created this issue (but this message is not displayed anymore, maybe you are already fixing things).

FYI record of Fabasoft rejoining this group "[W3C Group Management] Fabasoft has joined the Accessible Rich Internet Applications Working Group":
* Date: Tue, 17 Dec 2024 06:16:50 +0000 https://lists.w3.org/Archives/Member/w3c-archive/2024Dec/0647.html
* Date: Tue, 17 Dec 2024 06:26:57 +0000 https://lists.w3.org/Archives/Member/w3c-archive/2024Dec/0648.html

**Comment by deniak** [comment]
@MarioBatusic, this problem occurs because when you re-joined the group, you selected the option 'my organization does not intend to participate in the group and simply makes the Patent Policy Licensing commitment'.
However, you, as a Fabasoft employee, joined the group, this generated this error. I've updated the option your provided and the warning is now gone.

**Comment by MarioBatusic** [comment]
I did'nt connect the checkbox with this option cognitively. Maybe because I am blind and use a screen reiding rpogram.

**Comment by deniak** [comment]
> I did'nt connect the checkbox with this option cognitively. Maybe because I am blind and use a screen reiding rpogram.

Thanks for the input. We'll see if there's an a11y with this page.
