### ISSUE TITLE
Content slider not working on documentation

### ISSUE THREAD

**Issue by jffraisse** [w3c/w3c-website#79]
Hello,

First of all thank you so much for all the work around standards and accessibility <3

There is an issue with content-slider component.

You can see it in [documentation](https://design-system.w3.org/components/slider.html), in ["open this in a new tab" example](https://design-system.w3.org/code/content-slider.html), and even in [business ecosystem template](https://design-system.w3.org/templates/business-ecosystem.html) . 

It seems library need a mandatory html element to construct slider as '.top-nav-item.has-children > a' return nothing and break js execution.

![Capture d’écran (487)](https://user-images.githubusercontent.com/17980465/144641605-de7d301b-720b-4d5a-b2b5-04008a87ba09.png)

I tried on chrome, edge, firefox, same result :/

**Comment by maries24** [comment]
Thank you for raising this issue @jffraisse 

There were two issues:

- A bug that was throwing the error in the console when no navigation was present on the page. And which is now fixed.
- The carousel that was not working.

The carousel was not working because the script to make it work has not been included in the page. This was due to a limitation to the package that generates the design system. I have found a workaround and now the carousel works (both on its own page and in the business ecosystem template).

I'm closing the issue. Feel free to re-open it if it still fails for you.

Thanks.
